[project]
name = "hse-subd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.4",
    "alembic-utils>=0.8.8",
    "psycopg>=3.3.3",
    "pytest>=9.0.2",
    "ruff>=0.15.5",
    "sqlalchemy>=2.0.48",
    "sqlalchemy-declarative-extensions>=0.16.8",
    "testcontainers>=4.14.1",
]

[dependency-groups]
dev = [
    "ty>=0.0.20",
]
