"""triggers

Revision ID: 6611b8d45bf5
Revises: e8313f0fd0ec
Create Date: 2026-03-05 12:10:57.867908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = '6611b8d45bf5'
down_revision: Union[str, Sequence[str], None] = 'e8313f0fd0ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_ensure_dealer_correct = PGFunction(
        schema="public",
        signature="ensure_dealer_correct()",
        definition="RETURNS TRIGGER AS $ensure_dealer$\n    DECLARE\n        table_type_ID integer;\n        should_be_supervised integer;\n        BEGIN\n            IF (TG_OP = 'INSERT') THEN\n                SELECT type_ID INTO table_type_ID FROM Tables WHERE table_ID = NEW.table_ID;\n                SELECT isSupervised INTO should_be_supervised FROM Game_types WHERE type_ID = table_type_ID;\n                IF (should_be_supervised = 1 AND NEW.staff_ID IS NULL) THEN\n                    RAISE EXCEPTION 'Game type % should be supervised, missing dealer for session %',\n                        table_type_ID, NEW.session_ID;\n                ELSIF (should_be_supervised = 0 AND NEW.staff_ID IS NOT NULL) THEN\n                    RAISE EXCEPTION 'Game type % should not be supervised, found dealer % for session %',\n                        table_type_ID, NEW.staff_ID, NEW.session_ID;\n                END IF;\n                \n            END IF;\n        END;\n    $ensure_dealer$ LANGUAGE plpgsql"
    )
    op.create_entity(public_ensure_dealer_correct)

    public_session_tables_ensure_dealer_trigger = PGTrigger(
        schema="public",
        signature="ensure_dealer_trigger",
        on_entity="public.session_tables",
        is_constraint=True,
        definition='AFTER INSERT ON public.session_tables DEFERRABLE INITIALLY DEFERRED\n        FOR EACH ROW EXECUTE FUNCTION ensure_dealer_correct()'
    )
    op.create_entity(public_session_tables_ensure_dealer_trigger)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_session_tables_ensure_dealer_trigger = PGTrigger(
        schema="public",
        signature="ensure_dealer_trigger",
        on_entity="public.session_tables",
        is_constraint=True,
        definition='AFTER INSERT ON public.session_tables DEFERRABLE INITIALLY DEFERRED\n        FOR EACH ROW EXECUTE FUNCTION ensure_dealer_correct()'
    )
    op.drop_entity(public_session_tables_ensure_dealer_trigger)

    public_ensure_dealer_correct = PGFunction(
        schema="public",
        signature="ensure_dealer_correct()",
        definition="RETURNS TRIGGER AS $ensure_dealer$\n    DECLARE\n        table_type_ID integer;\n        should_be_supervised integer;\n        BEGIN\n            IF (TG_OP = 'INSERT') THEN\n                SELECT type_ID INTO table_type_ID FROM Tables WHERE table_ID = NEW.table_ID;\n                SELECT isSupervised INTO should_be_supervised FROM Game_types WHERE type_ID = table_type_ID;\n                IF (should_be_supervised = 1 AND NEW.staff_ID IS NULL) THEN\n                    RAISE EXCEPTION 'Game type % should be supervised, missing dealer for session %',\n                        table_type_ID, NEW.session_ID;\n                ELSIF (should_be_supervised = 0 AND NEW.staff_ID IS NOT NULL) THEN\n                    RAISE EXCEPTION 'Game type % should not be supervised, found dealer % for session %',\n                        table_type_ID, NEW.staff_ID, NEW.session_ID;\n                END IF;\n                \n            END IF;\n        END;\n    $ensure_dealer$ LANGUAGE plpgsql"
    )
    op.drop_entity(public_ensure_dealer_correct)

    # ### end Alembic commands ###
