"""triggers

Revision ID: 7af387664104
Revises: 118ace94455d
Create Date: 2026-03-06 19:38:33.433381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = '7af387664104'
down_revision: Union[str, Sequence[str], None] = '118ace94455d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_ensure_dealer_correct = PGFunction(
        schema="public",
        signature="ensure_dealer_correct()",
        definition="RETURNS TRIGGER AS $ensure_dealer$\n    DECLARE\n        table_type_id integer;\n        should_be_supervised integer;\n        BEGIN\n            IF (TG_OP = 'INSERT') THEN\n                SELECT type_id INTO table_type_id FROM Tables WHERE table_id = NEW.table_id;\n                SELECT is_supervised INTO should_be_supervised FROM game_types WHERE type_id = table_type_id;\n                IF (should_be_supervised = 1 AND NEW.staff_id IS NULL) THEN\n                    RAISE EXCEPTION 'Game type % should be supervised, missing dealer for session %',\n                        table_type_id, NEW.session_id;\n                ELSIF (should_be_supervised = 0 AND NEW.staff_id IS NOT NULL) THEN\n                    RAISE EXCEPTION 'Game type % should not be supervised, found dealer % for session %',\n                        table_type_id, NEW.staff_id, NEW.session_id;\n                END IF;\n                \n            END IF;\n            RETURN NULL;\n        END;\n    $ensure_dealer$ LANGUAGE plpgsql"
    )
    op.create_entity(public_ensure_dealer_correct)

    public_update_card_bid = PGFunction(
        schema="public",
        signature="update_card_bid()",
        definition="RETURNS TRIGGER AS $update_card_bid$\n    DECLARE\n        card_balance integer;\n    BEGIN\n        IF (TG_OP = 'INSERT') THEN\n            SELECT balance FROM card INTO card_balance;\n            IF (NEW.bid_amount > card_balance) THEN\n                RAISE EXCEPTION 'Cannot bet more money than the card has';\n            END IF;\n            IF (NEW.money_gain = 0) THEN\n                UPDATE card SET balance = balance - NEW.bid_amount WHERE card_id = NEW.card_id;\n            ELSE\n                UPDATE card SET balance = balance + NEW.money_gain WHERE card_id = NEW.card_id;\n            END IF;\n        END IF;\n        RETURN NULL;\n    END;\n    $update_card_bid$ LANGUAGE plpgsql"
    )
    op.create_entity(public_update_card_bid)

    public_session_tables_ensure_dealer_trigger = PGTrigger(
        schema="public",
        signature="ensure_dealer_trigger",
        on_entity="public.session_tables",
        is_constraint=True,
        definition='AFTER INSERT ON public.session_tables\n        FOR EACH ROW EXECUTE FUNCTION ensure_dealer_correct()'
    )
    op.create_entity(public_session_tables_ensure_dealer_trigger)

    public_card_bid_within_session_update_card_bid_trigger = PGTrigger(
        schema="public",
        signature="update_card_bid_trigger",
        on_entity="public.card_bid_within_session",
        is_constraint=False,
        definition='AFTER INSERT ON public.card_bid_within_session\n        FOR EACH ROW EXECUTE FUNCTION update_card_bid()'
    )
    op.create_entity(public_card_bid_within_session_update_card_bid_trigger)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_card_bid_within_session_update_card_bid_trigger = PGTrigger(
        schema="public",
        signature="update_card_bid_trigger",
        on_entity="public.card_bid_within_session",
        is_constraint=False,
        definition='AFTER INSERT ON public.card_bid_within_session\n        FOR EACH ROW EXECUTE FUNCTION update_card_bid()'
    )
    op.drop_entity(public_card_bid_within_session_update_card_bid_trigger)

    public_session_tables_ensure_dealer_trigger = PGTrigger(
        schema="public",
        signature="ensure_dealer_trigger",
        on_entity="public.session_tables",
        is_constraint=True,
        definition='AFTER INSERT ON public.session_tables\n        FOR EACH ROW EXECUTE FUNCTION ensure_dealer_correct()'
    )
    op.drop_entity(public_session_tables_ensure_dealer_trigger)

    public_update_card_bid = PGFunction(
        schema="public",
        signature="update_card_bid()",
        definition="RETURNS TRIGGER AS $update_card_bid$\n    DECLARE\n        card_balance integer;\n    BEGIN\n        IF (TG_OP = 'INSERT') THEN\n            SELECT balance FROM card INTO card_balance;\n            IF (NEW.bid_amount > card_balance) THEN\n                RAISE EXCEPTION 'Cannot bet more money than the card has';\n            END IF;\n            IF (NEW.money_gain = 0) THEN\n                UPDATE card SET balance = balance - NEW.bid_amount WHERE card_id = NEW.card_id;\n            ELSE\n                UPDATE card SET balance = balance + NEW.money_gain WHERE card_id = NEW.card_id;\n            END IF;\n        END IF;\n        RETURN NULL;\n    END;\n    $update_card_bid$ LANGUAGE plpgsql"
    )
    op.drop_entity(public_update_card_bid)

    public_ensure_dealer_correct = PGFunction(
        schema="public",
        signature="ensure_dealer_correct()",
        definition="RETURNS TRIGGER AS $ensure_dealer$\n    DECLARE\n        table_type_id integer;\n        should_be_supervised integer;\n        BEGIN\n            IF (TG_OP = 'INSERT') THEN\n                SELECT type_id INTO table_type_id FROM Tables WHERE table_id = NEW.table_id;\n                SELECT is_supervised INTO should_be_supervised FROM game_types WHERE type_id = table_type_id;\n                IF (should_be_supervised = 1 AND NEW.staff_id IS NULL) THEN\n                    RAISE EXCEPTION 'Game type % should be supervised, missing dealer for session %',\n                        table_type_id, NEW.session_id;\n                ELSIF (should_be_supervised = 0 AND NEW.staff_id IS NOT NULL) THEN\n                    RAISE EXCEPTION 'Game type % should not be supervised, found dealer % for session %',\n                        table_type_id, NEW.staff_id, NEW.session_id;\n                END IF;\n                \n            END IF;\n            RETURN NULL;\n        END;\n    $ensure_dealer$ LANGUAGE plpgsql"
    )
    op.drop_entity(public_ensure_dealer_correct)

    # ### end Alembic commands ###
