"""initial

Revision ID: b45c6af4aeb1
Revises:
Create Date: 2026-03-10 14:12:15.876861

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b45c6af4aeb1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "card",
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("balance", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("card_id"),
    )
    op.create_table(
        "clients",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("surname", sa.String(length=20), nullable=False),
        sa.Column("deposit", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(length=20), nullable=False),
        sa.Column("credit", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(length=20), nullable=True),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "drinks",
        sa.Column("drink_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("volume", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("drink_id"),
    )
    op.create_table(
        "game_types",
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("game_type", sa.String(length=20), nullable=False),
        sa.Column("is_supervised", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("type_id"),
    )
    op.create_table(
        "session",
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_table(
        "staff",
        sa.Column("staff_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("surname", sa.String(length=20), nullable=False),
        sa.Column("address", sa.String(length=20), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("staff_id"),
    )
    op.create_table(
        "bar_supplies",
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("drink_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["drink_id"],
            ["drinks.drink_id"],
        ),
        sa.PrimaryKeyConstraint("drink_id"),
    )
    op.create_table(
        "bartenders",
        sa.Column("staff_id", sa.Integer(), nullable=False),
        sa.Column("performance_rating", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "(performance_rating >= 0 AND performance_rating <= 5) OR performance_rating IS NULL"
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["staff.staff_id"],
        ),
        sa.PrimaryKeyConstraint("staff_id"),
    )
    op.create_table(
        "card_bid_within_session",
        sa.Column("bid_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("bid_amount", sa.Integer(), nullable=False),
        sa.Column("money_gain", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["card.card_id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.session_id"],
        ),
        sa.PrimaryKeyConstraint("bid_id"),
    )
    op.create_table(
        "cards_to_clients_dispenser",
        sa.Column("dispenser_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("entry_time", sa.DateTime(), nullable=False),
        sa.Column("abandon_time", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["card.card_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["clients.user_id"],
        ),
        sa.PrimaryKeyConstraint("dispenser_id"),
    )
    op.create_table(
        "dealers",
        sa.Column("staff_id", sa.Integer(), nullable=False),
        sa.Column("qualification", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["staff.staff_id"],
        ),
        sa.PrimaryKeyConstraint("staff_id"),
    )
    op.create_table(
        "security",
        sa.Column("staff_id", sa.Integer(), nullable=False),
        sa.Column("zone", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["staff.staff_id"],
        ),
        sa.PrimaryKeyConstraint("staff_id"),
    )
    op.create_table(
        "tables",
        sa.Column("table_id", sa.Integer(), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("balance", sa.Integer(), nullable=False),
        sa.Column("opening_time", sa.DateTime(), nullable=False),
        sa.Column("closing_time", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["game_types.type_id"],
        ),
        sa.PrimaryKeyConstraint("table_id"),
    )
    op.create_table(
        "orders",
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("order_time", sa.DateTime(), nullable=False),
        sa.Column("staff_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["bartenders.staff_id"],
        ),
        sa.PrimaryKeyConstraint("order_id"),
    )
    op.create_table(
        "session_tables",
        sa.Column("session_to_table_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("table_id", sa.Integer(), nullable=False),
        sa.Column("staff_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.session_id"],
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["dealers.staff_id"],
        ),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["tables.table_id"],
        ),
        sa.PrimaryKeyConstraint("session_to_table_id"),
    )
    op.create_table(
        "split_order_by_card",
        sa.Column("split_order_id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("drink_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.CheckConstraint("quantity >= 1"),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["card.card_id"],
        ),
        sa.ForeignKeyConstraint(
            ["drink_id"],
            ["drinks.drink_id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.order_id"],
        ),
        sa.PrimaryKeyConstraint("split_order_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("split_order_by_card")
    op.drop_table("session_tables")
    op.drop_table("orders")
    op.drop_table("tables")
    op.drop_table("security")
    op.drop_table("dealers")
    op.drop_table("cards_to_clients_dispenser")
    op.drop_table("card_bid_within_session")
    op.drop_table("bartenders")
    op.drop_table("bar_supplies")
    op.drop_table("staff")
    op.drop_table("session")
    op.drop_table("game_types")
    op.drop_table("drinks")
    op.drop_table("clients")
    op.drop_table("card")
    # ### end Alembic commands ###
