"""initial migration

Revision ID: cc5de6cc8919
Revises: 
Create Date: 2026-03-05 00:23:28.815525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc5de6cc8919'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Card',
    sa.Column('card_ID', sa.Integer(), nullable=False),
    sa.Column('user_ID', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('card_ID')
    )
    op.create_table('Clients',
    sa.Column('user_ID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('surname', sa.String(length=20), nullable=True),
    sa.Column('deposit', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=20), nullable=True),
    sa.Column('credit', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_ID')
    )
    op.create_table('Drinks',
    sa.Column('drink_ID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('drink_ID')
    )
    op.create_table('Game_types',
    sa.Column('type_ID', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(length=20), nullable=False),
    sa.Column('isSupervised', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('type_ID')
    )
    op.create_table('Session',
    sa.Column('session_ID', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('session_ID')
    )
    op.create_table('Staff',
    sa.Column('staff_ID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('surname', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('staff_ID')
    )
    op.create_table('Bar_supplies',
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('drink_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drink_ID'], ['Drinks.drink_ID'], ),
    sa.PrimaryKeyConstraint('drink_ID')
    )
    op.create_table('Bartenders',
    sa.Column('staff_ID', sa.Integer(), nullable=False),
    sa.Column('performance_rating', sa.Integer(), nullable=True),
    sa.CheckConstraint('performance_rating >= 0 AND performance_rating <= 5'),
    sa.ForeignKeyConstraint(['staff_ID'], ['Staff.staff_ID'], ),
    sa.PrimaryKeyConstraint('staff_ID')
    )
    op.create_table('CardToClientsDispenser',
    sa.Column('dispenser_ID', sa.Integer(), nullable=False),
    sa.Column('user_ID', sa.Integer(), nullable=False),
    sa.Column('card_ID', sa.Integer(), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=True),
    sa.Column('abandon_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_ID'], ['Card.card_ID'], ),
    sa.ForeignKeyConstraint(['user_ID'], ['Clients.user_ID'], ),
    sa.PrimaryKeyConstraint('dispenser_ID')
    )
    op.create_table('Card_Bid_within_Session',
    sa.Column('bid_ID', sa.Integer(), nullable=False),
    sa.Column('session_ID', sa.Integer(), nullable=False),
    sa.Column('card_ID', sa.Integer(), nullable=False),
    sa.Column('bid_amount', sa.Integer(), nullable=True),
    sa.Column('money_gain', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_ID'], ['Card.card_ID'], ),
    sa.ForeignKeyConstraint(['session_ID'], ['Session.session_ID'], ),
    sa.PrimaryKeyConstraint('bid_ID')
    )
    op.create_table('Dealers',
    sa.Column('staff_ID', sa.Integer(), nullable=False),
    sa.Column('qualification', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['staff_ID'], ['Staff.staff_ID'], ),
    sa.PrimaryKeyConstraint('staff_ID')
    )
    op.create_table('Security',
    sa.Column('staff_ID', sa.Integer(), nullable=False),
    sa.Column('zone', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['staff_ID'], ['Staff.staff_ID'], ),
    sa.PrimaryKeyConstraint('staff_ID')
    )
    op.create_table('Tables',
    sa.Column('table_ID', sa.Integer(), nullable=False),
    sa.Column('type_ID', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('openning_time', sa.DateTime(), nullable=True),
    sa.Column('closing_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['type_ID'], ['Game_types.type_ID'], ),
    sa.PrimaryKeyConstraint('table_ID')
    )
    op.create_table('Orders',
    sa.Column('order_ID', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('order_time', sa.DateTime(), nullable=True),
    sa.Column('staff_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['staff_ID'], ['Bartenders.staff_ID'], ),
    sa.PrimaryKeyConstraint('order_ID')
    )
    op.create_table('Session_Tables',
    sa.Column('session_to_table_ID', sa.Integer(), nullable=False),
    sa.Column('session_ID', sa.Integer(), nullable=False),
    sa.Column('table_ID', sa.Integer(), nullable=False),
    sa.Column('staff_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_ID'], ['Session.session_ID'], ),
    sa.ForeignKeyConstraint(['staff_ID'], ['Dealers.staff_ID'], ),
    sa.ForeignKeyConstraint(['table_ID'], ['Tables.table_ID'], ),
    sa.PrimaryKeyConstraint('session_to_table_ID')
    )
    op.create_table('Split_Order_by_Card',
    sa.Column('split_order_ID', sa.Integer(), nullable=False),
    sa.Column('card_ID', sa.Integer(), nullable=False),
    sa.Column('order_ID', sa.Integer(), nullable=False),
    sa.Column('drink_ID', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_ID'], ['Card.card_ID'], ),
    sa.ForeignKeyConstraint(['drink_ID'], ['Drinks.drink_ID'], ),
    sa.ForeignKeyConstraint(['order_ID'], ['Orders.order_ID'], ),
    sa.PrimaryKeyConstraint('split_order_ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Split_Order_by_Card')
    op.drop_table('Session_Tables')
    op.drop_table('Orders')
    op.drop_table('Tables')
    op.drop_table('Security')
    op.drop_table('Dealers')
    op.drop_table('Card_Bid_within_Session')
    op.drop_table('CardToClientsDispenser')
    op.drop_table('Bartenders')
    op.drop_table('Bar_supplies')
    op.drop_table('Staff')
    op.drop_table('Session')
    op.drop_table('Game_types')
    op.drop_table('Drinks')
    op.drop_table('Clients')
    op.drop_table('Card')
    # ### end Alembic commands ###
