"""triggers

Revision ID: ce898cfe72e3
Revises: bab89c850b88
Create Date: 2026-03-10 14:06:15.854592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = 'ce898cfe72e3'
down_revision: Union[str, Sequence[str], None] = 'bab89c850b88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""CREATE ROLE "staff" WITH NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'staff';""")
    op.execute("""CREATE ROLE "players" WITH NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'players';""")
    op.execute("""CREATE ROLE "card_reader" WITH NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOLOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'card_reader';""")
    op.execute("""CREATE ROLE "card_dispenser" WITH NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOLOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'card_dispenser';""")
    op.execute("""CREATE ROLE "order_terminal" WITH NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOLOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'order_terminal';""")
    op.execute("""CREATE ROLE "bid_terminal" WITH NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOLOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'bid_terminal';""")
    op.execute("""CREATE ROLE "bartenders" WITH NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'bartenders' IN ROLE "staff";""")
    op.execute("""CREATE ROLE "security" WITH NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'security' IN ROLE "staff";""")
    op.execute("""CREATE ROLE "dealers" WITH NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'dealers' IN ROLE "staff";""")
    op.execute(sa.text("""GRANT USAGE ON SEQUENCE "card_bid_within_session_bid_id_seq" TO "bid_terminal";"""))
    op.execute(sa.text("""GRANT USAGE ON SEQUENCE "card_card_id_seq" TO "card_dispenser";"""))
    op.execute(sa.text("""GRANT USAGE ON SEQUENCE "cards_to_clients_dispenser_dispenser_id_seq" TO "card_dispenser";"""))
    op.execute(sa.text("""GRANT USAGE ON SEQUENCE "orders_order_id_seq" TO "order_terminal";"""))
    op.execute(sa.text("""GRANT USAGE ON SEQUENCE "split_order_by_card_split_order_id_seq" TO "order_terminal";"""))
    op.execute(sa.text("""GRANT SELECT ON TABLE "bar_supplies" TO "bartenders";"""))
    op.execute(sa.text("""GRANT SELECT, UPDATE ON TABLE "bar_supplies" TO "order_terminal";"""))
    op.execute(sa.text("""GRANT SELECT ON TABLE "bartenders" TO "bartenders";"""))
    op.execute(sa.text("""GRANT SELECT ON TABLE "bartenders" TO "order_terminal";"""))
    op.execute(sa.text("""GRANT SELECT, UPDATE ON TABLE "card" TO "bid_terminal";"""))
    op.execute(sa.text("""GRANT SELECT, INSERT ON TABLE "card" TO "card_dispenser";"""))
    op.execute(sa.text("""GRANT SELECT ON TABLE "card" TO "card_reader";"""))
    op.execute(sa.text("""GRANT SELECT, UPDATE ON TABLE "card" TO "order_terminal";"""))
    op.execute(sa.text("""GRANT SELECT, INSERT ON TABLE "card_bid_within_session" TO "bid_terminal";"""))
    op.execute(sa.text("""GRANT SELECT ON TABLE "card_bid_within_session" TO "dealers";"""))
    op.execute(sa.text("""GRANT SELECT ON TABLE "card_bid_within_session" TO "players";"""))
    op.execute(sa.text("""GRANT INSERT, SELECT ON TABLE "cards_to_clients_dispenser" TO "card_dispenser";"""))
    op.execute(sa.text("""GRANT SELECT ON TABLE "cards_to_clients_dispenser" TO "security";"""))
    op.execute(sa.text("""GRANT SELECT ON TABLE "clients" TO "security";"""))
    op.execute(sa.text("""GRANT SELECT ON TABLE "dealers" TO "dealers";"""))
    op.execute(sa.text("""GRANT SELECT ON TABLE "drinks" TO "bartenders";"""))
    op.execute(sa.text("""GRANT SELECT ON TABLE "drinks" TO "order_terminal";"""))
    op.execute(sa.text("""GRANT SELECT ON TABLE "game_types" TO "dealers";"""))
    op.execute(sa.text("""GRANT SELECT ON TABLE "game_types" TO "players";"""))
    op.execute(sa.text("""GRANT SELECT ON TABLE "orders" TO "bartenders";"""))
    op.execute(sa.text("""GRANT UPDATE, INSERT, SELECT ON TABLE "orders" TO "order_terminal";"""))
    op.execute(sa.text("""GRANT SELECT ON TABLE "security" TO "security";"""))
    op.execute(sa.text("""GRANT SELECT ON TABLE "session" TO "bid_terminal";"""))
    op.execute(sa.text("""GRANT SELECT ON TABLE "session" TO "dealers";"""))
    op.execute(sa.text("""GRANT SELECT ON TABLE "session" TO "players";"""))
    op.execute(sa.text("""GRANT SELECT ON TABLE "session_tables" TO "bid_terminal";"""))
    op.execute(sa.text("""GRANT SELECT ON TABLE "session_tables" TO "dealers";"""))
    op.execute(sa.text("""GRANT SELECT ON TABLE "session_tables" TO "players";"""))
    op.execute(sa.text("""GRANT SELECT ON TABLE "split_order_by_card" TO "bartenders";"""))
    op.execute(sa.text("""GRANT SELECT, INSERT ON TABLE "split_order_by_card" TO "order_terminal";"""))
    op.execute(sa.text("""GRANT SELECT ON TABLE "staff" TO "staff";"""))
    op.execute(sa.text("""GRANT UPDATE ON TABLE "tables" TO "bid_terminal";"""))
    op.execute(sa.text("""GRANT SELECT ON TABLE "tables" TO "dealers";"""))
    op.execute(sa.text("""GRANT SELECT ON TABLE "tables" TO "players";"""))
    public_ensure_dealer_correct = PGFunction(
        schema="public",
        signature="ensure_dealer_correct()",
        definition="RETURNS TRIGGER AS $ensure_dealer$\n    DECLARE\n        table_type_id integer;\n        should_be_supervised boolean;\n        BEGIN\n            IF (TG_OP = 'INSERT') THEN\n                SELECT type_id INTO table_type_id FROM Tables WHERE table_id = NEW.table_id;\n                SELECT is_supervised INTO should_be_supervised FROM game_types WHERE type_id = table_type_id;\n                IF (should_be_supervised = true AND NEW.staff_id IS NULL) THEN\n                    RAISE EXCEPTION 'Game type % should be supervised, missing dealer for session %',\n                        table_type_id, NEW.session_id;\n                ELSIF (should_be_supervised = false AND NEW.staff_id IS NOT NULL) THEN\n                    RAISE EXCEPTION 'Game type % should not be supervised, found dealer % for session %',\n                        table_type_id, NEW.staff_id, NEW.session_id;\n                END IF;\n                \n            END IF;\n            RETURN NULL;\n        END;\n    $ensure_dealer$ LANGUAGE plpgsql"
    )
    op.create_entity(public_ensure_dealer_correct)

    public_update_card_bid = PGFunction(
        schema="public",
        signature="update_card_bid()",
        definition="RETURNS TRIGGER AS $update_card_bid$\n    DECLARE\n        card_balance integer;\n        money_delta integer;\n    BEGIN\n        IF (TG_OP = 'INSERT') THEN\n            SELECT balance FROM card INTO card_balance WHERE card_id = NEW.card_id;\n            money_delta := NEW.bid_amount - NEW.money_gain;\n            IF (NEW.bid_amount > card_balance) THEN\n                RAISE EXCEPTION 'Cannot bet more money than the card has';\n            END IF;\n            UPDATE card SET balance = balance - money_delta WHERE card_id = NEW.card_id;\n            UPDATE tables SET balance = balance + money_delta WHERE table_id = (SELECT table_id FROM session_tables WHERE session_id = NEW.session_id);\n        END IF;\n        RETURN NULL;\n    END;\n    $update_card_bid$ LANGUAGE plpgsql"
    )
    op.create_entity(public_update_card_bid)

    public_update_card_order = PGFunction(
        schema="public",
        signature="update_card_order()",
        definition="RETURNS TRIGGER AS $update_card_order$\n    DECLARE\n        card_balance integer;\n        order_total integer;\n        remaining_quantity integer;\n    BEGIN\n        IF (TG_OP = 'INSERT') THEN\n            SELECT balance FROM card INTO card_balance WHERE card_id = NEW.card_id;\n            SELECT price * NEW.quantity FROM drinks INTO order_total WHERE drink_id = NEW.drink_id;\n\n            IF (order_total > card_balance) THEN\n                RAISE EXCEPTION 'Cannot place an order with more total than the card has';\n            END IF;\n\n            SELECT quantity FROM bar_supplies INTO remaining_quantity WHERE drink_id = NEW.drink_id;\n\n            IF (NEW.quantity > remaining_quantity) THEN\n                RAISE EXCEPTION 'Cannot place an order for more items than there are in supplies';\n            END IF;\n\n            UPDATE orders SET total = total + order_total WHERE order_id = NEW.order_id;\n            UPDATE card SET balance = balance - order_total WHERE card_id = NEW.card_id;\n            UPDATE bar_supplies SET quantity = quantity - NEW.quantity WHERE drink_id = NEW.drink_id;\n        END IF;\n        RETURN NULL;\n    END;\n    $update_card_order$ LANGUAGE plpgsql"
    )
    op.create_entity(public_update_card_order)

    public_session_tables_ensure_dealer_trigger = PGTrigger(
        schema="public",
        signature="ensure_dealer_trigger",
        on_entity="public.session_tables",
        is_constraint=True,
        definition='AFTER INSERT ON public.session_tables\n        FOR EACH ROW EXECUTE FUNCTION ensure_dealer_correct()'
    )
    op.create_entity(public_session_tables_ensure_dealer_trigger)

    public_card_bid_within_session_update_card_bid_trigger = PGTrigger(
        schema="public",
        signature="update_card_bid_trigger",
        on_entity="public.card_bid_within_session",
        is_constraint=False,
        definition='AFTER INSERT ON public.card_bid_within_session\n        FOR EACH ROW EXECUTE FUNCTION update_card_bid()'
    )
    op.create_entity(public_card_bid_within_session_update_card_bid_trigger)

    public_split_order_by_card_update_card_order_trigger = PGTrigger(
        schema="public",
        signature="update_card_order_trigger",
        on_entity="public.split_order_by_card",
        is_constraint=False,
        definition='AFTER INSERT ON public.split_order_by_card\n        FOR EACH ROW EXECUTE FUNCTION update_card_order()'
    )
    op.create_entity(public_split_order_by_card_update_card_order_trigger)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_split_order_by_card_update_card_order_trigger = PGTrigger(
        schema="public",
        signature="update_card_order_trigger",
        on_entity="public.split_order_by_card",
        is_constraint=False,
        definition='AFTER INSERT ON public.split_order_by_card\n        FOR EACH ROW EXECUTE FUNCTION update_card_order()'
    )
    op.drop_entity(public_split_order_by_card_update_card_order_trigger)

    public_card_bid_within_session_update_card_bid_trigger = PGTrigger(
        schema="public",
        signature="update_card_bid_trigger",
        on_entity="public.card_bid_within_session",
        is_constraint=False,
        definition='AFTER INSERT ON public.card_bid_within_session\n        FOR EACH ROW EXECUTE FUNCTION update_card_bid()'
    )
    op.drop_entity(public_card_bid_within_session_update_card_bid_trigger)

    public_session_tables_ensure_dealer_trigger = PGTrigger(
        schema="public",
        signature="ensure_dealer_trigger",
        on_entity="public.session_tables",
        is_constraint=True,
        definition='AFTER INSERT ON public.session_tables\n        FOR EACH ROW EXECUTE FUNCTION ensure_dealer_correct()'
    )
    op.drop_entity(public_session_tables_ensure_dealer_trigger)

    public_update_card_order = PGFunction(
        schema="public",
        signature="update_card_order()",
        definition="RETURNS TRIGGER AS $update_card_order$\n    DECLARE\n        card_balance integer;\n        order_total integer;\n        remaining_quantity integer;\n    BEGIN\n        IF (TG_OP = 'INSERT') THEN\n            SELECT balance FROM card INTO card_balance WHERE card_id = NEW.card_id;\n            SELECT price * NEW.quantity FROM drinks INTO order_total WHERE drink_id = NEW.drink_id;\n\n            IF (order_total > card_balance) THEN\n                RAISE EXCEPTION 'Cannot place an order with more total than the card has';\n            END IF;\n\n            SELECT quantity FROM bar_supplies INTO remaining_quantity WHERE drink_id = NEW.drink_id;\n\n            IF (NEW.quantity > remaining_quantity) THEN\n                RAISE EXCEPTION 'Cannot place an order for more items than there are in supplies';\n            END IF;\n\n            UPDATE orders SET total = total + order_total WHERE order_id = NEW.order_id;\n            UPDATE card SET balance = balance - order_total WHERE card_id = NEW.card_id;\n            UPDATE bar_supplies SET quantity = quantity - NEW.quantity WHERE drink_id = NEW.drink_id;\n        END IF;\n        RETURN NULL;\n    END;\n    $update_card_order$ LANGUAGE plpgsql"
    )
    op.drop_entity(public_update_card_order)

    public_update_card_bid = PGFunction(
        schema="public",
        signature="update_card_bid()",
        definition="RETURNS TRIGGER AS $update_card_bid$\n    DECLARE\n        card_balance integer;\n        money_delta integer;\n    BEGIN\n        IF (TG_OP = 'INSERT') THEN\n            SELECT balance FROM card INTO card_balance WHERE card_id = NEW.card_id;\n            money_delta := NEW.bid_amount - NEW.money_gain;\n            IF (NEW.bid_amount > card_balance) THEN\n                RAISE EXCEPTION 'Cannot bet more money than the card has';\n            END IF;\n            UPDATE card SET balance = balance - money_delta WHERE card_id = NEW.card_id;\n            UPDATE tables SET balance = balance + money_delta WHERE table_id = (SELECT table_id FROM session_tables WHERE session_id = NEW.session_id);\n        END IF;\n        RETURN NULL;\n    END;\n    $update_card_bid$ LANGUAGE plpgsql"
    )
    op.drop_entity(public_update_card_bid)

    public_ensure_dealer_correct = PGFunction(
        schema="public",
        signature="ensure_dealer_correct()",
        definition="RETURNS TRIGGER AS $ensure_dealer$\n    DECLARE\n        table_type_id integer;\n        should_be_supervised boolean;\n        BEGIN\n            IF (TG_OP = 'INSERT') THEN\n                SELECT type_id INTO table_type_id FROM Tables WHERE table_id = NEW.table_id;\n                SELECT is_supervised INTO should_be_supervised FROM game_types WHERE type_id = table_type_id;\n                IF (should_be_supervised = true AND NEW.staff_id IS NULL) THEN\n                    RAISE EXCEPTION 'Game type % should be supervised, missing dealer for session %',\n                        table_type_id, NEW.session_id;\n                ELSIF (should_be_supervised = false AND NEW.staff_id IS NOT NULL) THEN\n                    RAISE EXCEPTION 'Game type % should not be supervised, found dealer % for session %',\n                        table_type_id, NEW.staff_id, NEW.session_id;\n                END IF;\n                \n            END IF;\n            RETURN NULL;\n        END;\n    $ensure_dealer$ LANGUAGE plpgsql"
    )
    op.drop_entity(public_ensure_dealer_correct)

    op.execute(sa.text("""REVOKE SELECT ON TABLE "tables" FROM "players";"""))
    op.execute(sa.text("""REVOKE SELECT ON TABLE "tables" FROM "dealers";"""))
    op.execute(sa.text("""REVOKE UPDATE ON TABLE "tables" FROM "bid_terminal";"""))
    op.execute(sa.text("""REVOKE SELECT ON TABLE "staff" FROM "staff";"""))
    op.execute(sa.text("""REVOKE SELECT, INSERT ON TABLE "split_order_by_card" FROM "order_terminal";"""))
    op.execute(sa.text("""REVOKE SELECT ON TABLE "split_order_by_card" FROM "bartenders";"""))
    op.execute(sa.text("""REVOKE SELECT ON TABLE "session_tables" FROM "players";"""))
    op.execute(sa.text("""REVOKE SELECT ON TABLE "session_tables" FROM "dealers";"""))
    op.execute(sa.text("""REVOKE SELECT ON TABLE "session_tables" FROM "bid_terminal";"""))
    op.execute(sa.text("""REVOKE SELECT ON TABLE "session" FROM "players";"""))
    op.execute(sa.text("""REVOKE SELECT ON TABLE "session" FROM "dealers";"""))
    op.execute(sa.text("""REVOKE SELECT ON TABLE "session" FROM "bid_terminal";"""))
    op.execute(sa.text("""REVOKE SELECT ON TABLE "security" FROM "security";"""))
    op.execute(sa.text("""REVOKE UPDATE, INSERT, SELECT ON TABLE "orders" FROM "order_terminal";"""))
    op.execute(sa.text("""REVOKE SELECT ON TABLE "orders" FROM "bartenders";"""))
    op.execute(sa.text("""REVOKE SELECT ON TABLE "game_types" FROM "players";"""))
    op.execute(sa.text("""REVOKE SELECT ON TABLE "game_types" FROM "dealers";"""))
    op.execute(sa.text("""REVOKE SELECT ON TABLE "drinks" FROM "order_terminal";"""))
    op.execute(sa.text("""REVOKE SELECT ON TABLE "drinks" FROM "bartenders";"""))
    op.execute(sa.text("""REVOKE SELECT ON TABLE "dealers" FROM "dealers";"""))
    op.execute(sa.text("""REVOKE SELECT ON TABLE "clients" FROM "security";"""))
    op.execute(sa.text("""REVOKE SELECT ON TABLE "cards_to_clients_dispenser" FROM "security";"""))
    op.execute(sa.text("""REVOKE INSERT, SELECT ON TABLE "cards_to_clients_dispenser" FROM "card_dispenser";"""))
    op.execute(sa.text("""REVOKE SELECT ON TABLE "card_bid_within_session" FROM "players";"""))
    op.execute(sa.text("""REVOKE SELECT ON TABLE "card_bid_within_session" FROM "dealers";"""))
    op.execute(sa.text("""REVOKE SELECT, INSERT ON TABLE "card_bid_within_session" FROM "bid_terminal";"""))
    op.execute(sa.text("""REVOKE SELECT, UPDATE ON TABLE "card" FROM "order_terminal";"""))
    op.execute(sa.text("""REVOKE SELECT ON TABLE "card" FROM "card_reader";"""))
    op.execute(sa.text("""REVOKE SELECT, INSERT ON TABLE "card" FROM "card_dispenser";"""))
    op.execute(sa.text("""REVOKE SELECT, UPDATE ON TABLE "card" FROM "bid_terminal";"""))
    op.execute(sa.text("""REVOKE SELECT ON TABLE "bartenders" FROM "order_terminal";"""))
    op.execute(sa.text("""REVOKE SELECT ON TABLE "bartenders" FROM "bartenders";"""))
    op.execute(sa.text("""REVOKE SELECT, UPDATE ON TABLE "bar_supplies" FROM "order_terminal";"""))
    op.execute(sa.text("""REVOKE SELECT ON TABLE "bar_supplies" FROM "bartenders";"""))
    op.execute(sa.text("""REVOKE USAGE ON SEQUENCE "split_order_by_card_split_order_id_seq" FROM "order_terminal";"""))
    op.execute(sa.text("""REVOKE USAGE ON SEQUENCE "orders_order_id_seq" FROM "order_terminal";"""))
    op.execute(sa.text("""REVOKE USAGE ON SEQUENCE "cards_to_clients_dispenser_dispenser_id_seq" FROM "card_dispenser";"""))
    op.execute(sa.text("""REVOKE USAGE ON SEQUENCE "card_card_id_seq" FROM "card_dispenser";"""))
    op.execute(sa.text("""REVOKE USAGE ON SEQUENCE "card_bid_within_session_bid_id_seq" FROM "bid_terminal";"""))
    op.execute("""DROP ROLE "dealers";""")
    op.execute("""DROP ROLE "security";""")
    op.execute("""DROP ROLE "bartenders";""")
    op.execute("""DROP ROLE "bid_terminal";""")
    op.execute("""DROP ROLE "order_terminal";""")
    op.execute("""DROP ROLE "card_dispenser";""")
    op.execute("""DROP ROLE "card_reader";""")
    op.execute("""DROP ROLE "players";""")
    op.execute("""DROP ROLE "staff";""")
    # ### end Alembic commands ###
