"""triggers

Revision ID: df34f36c2502
Revises: 58d93c64ad83
Create Date: 2026-03-08 16:18:21.194208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = 'df34f36c2502'
down_revision: Union[str, Sequence[str], None] = '58d93c64ad83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_ensure_dealer_correct = PGFunction(
        schema="public",
        signature="ensure_dealer_correct()",
        definition="RETURNS TRIGGER AS $ensure_dealer$\n    DECLARE\n        table_type_id integer;\n        should_be_supervised boolean;\n        BEGIN\n            IF (TG_OP = 'INSERT') THEN\n                SELECT type_id INTO table_type_id FROM Tables WHERE table_id = NEW.table_id;\n                SELECT is_supervised INTO should_be_supervised FROM game_types WHERE type_id = table_type_id;\n                IF (should_be_supervised = 1 AND NEW.staff_id IS NULL) THEN\n                    RAISE EXCEPTION 'Game type % should be supervised, missing dealer for session %',\n                        table_type_id, NEW.session_id;\n                ELSIF (should_be_supervised = 0 AND NEW.staff_id IS NOT NULL) THEN\n                    RAISE EXCEPTION 'Game type % should not be supervised, found dealer % for session %',\n                        table_type_id, NEW.staff_id, NEW.session_id;\n                END IF;\n                \n            END IF;\n            RETURN NULL;\n        END;\n    $ensure_dealer$ LANGUAGE plpgsql"
    )
    op.create_entity(public_ensure_dealer_correct)

    public_update_card_bid = PGFunction(
        schema="public",
        signature="update_card_bid()",
        definition="RETURNS TRIGGER AS $update_card_bid$\n    DECLARE\n        card_balance integer;\n    BEGIN\n        IF (TG_OP = 'INSERT') THEN\n            SELECT balance FROM card INTO card_balance WHERE card_id = NEW.card_id;\n            IF (NEW.bid_amount > card_balance) THEN\n                RAISE EXCEPTION 'Cannot bet more money than the card has';\n            END IF;\n            UPDATE card SET balance = balance - NEW.bid_amount + NEW.money_gain WHERE card_id = NEW.card_id;\n        END IF;\n        RETURN NULL;\n    END;\n    $update_card_bid$ LANGUAGE plpgsql"
    )
    op.create_entity(public_update_card_bid)

    public_update_card_order = PGFunction(
        schema="public",
        signature="update_card_order()",
        definition="RETURNS TRIGGER AS $update_card_order$\n    DECLARE\n        card_balance integer;\n        order_total integer;\n        remaining_quantity integer;\n    BEGIN\n        IF (TG_OP = 'INSERT') THEN\n            SELECT balance FROM card INTO card_balance WHERE card_id = NEW.card_id;\n            SELECT price * NEW.quantity FROM drinks INTO order_total WHERE drink_id = NEW.drink_id;\n\n            IF (order_total > card_balance) THEN\n                RAISE EXCEPTION 'Cannot place an order with more total than the card has';\n            END IF;\n\n            SELECT quantity FROM bar_supplies INTO remaining_quantity WHERE drink_id = NEW.drink_id;\n\n            IF (NEW.quantity > remaining_quantity) THEN\n                RAISE EXCEPTION 'Cannot place an order for more items than there are in supplies';\n            END IF;\n\n            UPDATE orders SET total = total + order_total WHERE order_id = NEW.order_id;\n            UPDATE card SET balance = balance - order_total WHERE card_id = NEW.card_id;\n            UPDATE bar_supplies SET quantity = quantity - NEW.quantity WHERE drink_id = NEW.drink_id;\n        END IF;\n        RETURN NULL;\n    END;\n    $update_card_order$ LANGUAGE plpgsql"
    )
    op.create_entity(public_update_card_order)

    public_session_tables_ensure_dealer_trigger = PGTrigger(
        schema="public",
        signature="ensure_dealer_trigger",
        on_entity="public.session_tables",
        is_constraint=True,
        definition='AFTER INSERT ON public.session_tables\n        FOR EACH ROW EXECUTE FUNCTION ensure_dealer_correct()'
    )
    op.create_entity(public_session_tables_ensure_dealer_trigger)

    public_card_bid_within_session_update_card_bid_trigger = PGTrigger(
        schema="public",
        signature="update_card_bid_trigger",
        on_entity="public.card_bid_within_session",
        is_constraint=False,
        definition='AFTER INSERT ON public.card_bid_within_session\n        FOR EACH ROW EXECUTE FUNCTION update_card_bid()'
    )
    op.create_entity(public_card_bid_within_session_update_card_bid_trigger)

    public_split_order_by_card_update_card_order_trigger = PGTrigger(
        schema="public",
        signature="update_card_order_trigger",
        on_entity="public.split_order_by_card",
        is_constraint=False,
        definition='AFTER INSERT ON public.split_order_by_card\n        FOR EACH ROW EXECUTE FUNCTION update_card_order()'
    )
    op.create_entity(public_split_order_by_card_update_card_order_trigger)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_split_order_by_card_update_card_order_trigger = PGTrigger(
        schema="public",
        signature="update_card_order_trigger",
        on_entity="public.split_order_by_card",
        is_constraint=False,
        definition='AFTER INSERT ON public.split_order_by_card\n        FOR EACH ROW EXECUTE FUNCTION update_card_order()'
    )
    op.drop_entity(public_split_order_by_card_update_card_order_trigger)

    public_card_bid_within_session_update_card_bid_trigger = PGTrigger(
        schema="public",
        signature="update_card_bid_trigger",
        on_entity="public.card_bid_within_session",
        is_constraint=False,
        definition='AFTER INSERT ON public.card_bid_within_session\n        FOR EACH ROW EXECUTE FUNCTION update_card_bid()'
    )
    op.drop_entity(public_card_bid_within_session_update_card_bid_trigger)

    public_session_tables_ensure_dealer_trigger = PGTrigger(
        schema="public",
        signature="ensure_dealer_trigger",
        on_entity="public.session_tables",
        is_constraint=True,
        definition='AFTER INSERT ON public.session_tables\n        FOR EACH ROW EXECUTE FUNCTION ensure_dealer_correct()'
    )
    op.drop_entity(public_session_tables_ensure_dealer_trigger)

    public_update_card_order = PGFunction(
        schema="public",
        signature="update_card_order()",
        definition="RETURNS TRIGGER AS $update_card_order$\n    DECLARE\n        card_balance integer;\n        order_total integer;\n        remaining_quantity integer;\n    BEGIN\n        IF (TG_OP = 'INSERT') THEN\n            SELECT balance FROM card INTO card_balance WHERE card_id = NEW.card_id;\n            SELECT price * NEW.quantity FROM drinks INTO order_total WHERE drink_id = NEW.drink_id;\n\n            IF (order_total > card_balance) THEN\n                RAISE EXCEPTION 'Cannot place an order with more total than the card has';\n            END IF;\n\n            SELECT quantity FROM bar_supplies INTO remaining_quantity WHERE drink_id = NEW.drink_id;\n\n            IF (NEW.quantity > remaining_quantity) THEN\n                RAISE EXCEPTION 'Cannot place an order for more items than there are in supplies';\n            END IF;\n\n            UPDATE orders SET total = total + order_total WHERE order_id = NEW.order_id;\n            UPDATE card SET balance = balance - order_total WHERE card_id = NEW.card_id;\n            UPDATE bar_supplies SET quantity = quantity - NEW.quantity WHERE drink_id = NEW.drink_id;\n        END IF;\n        RETURN NULL;\n    END;\n    $update_card_order$ LANGUAGE plpgsql"
    )
    op.drop_entity(public_update_card_order)

    public_update_card_bid = PGFunction(
        schema="public",
        signature="update_card_bid()",
        definition="RETURNS TRIGGER AS $update_card_bid$\n    DECLARE\n        card_balance integer;\n    BEGIN\n        IF (TG_OP = 'INSERT') THEN\n            SELECT balance FROM card INTO card_balance WHERE card_id = NEW.card_id;\n            IF (NEW.bid_amount > card_balance) THEN\n                RAISE EXCEPTION 'Cannot bet more money than the card has';\n            END IF;\n            UPDATE card SET balance = balance - NEW.bid_amount + NEW.money_gain WHERE card_id = NEW.card_id;\n        END IF;\n        RETURN NULL;\n    END;\n    $update_card_bid$ LANGUAGE plpgsql"
    )
    op.drop_entity(public_update_card_bid)

    public_ensure_dealer_correct = PGFunction(
        schema="public",
        signature="ensure_dealer_correct()",
        definition="RETURNS TRIGGER AS $ensure_dealer$\n    DECLARE\n        table_type_id integer;\n        should_be_supervised boolean;\n        BEGIN\n            IF (TG_OP = 'INSERT') THEN\n                SELECT type_id INTO table_type_id FROM Tables WHERE table_id = NEW.table_id;\n                SELECT is_supervised INTO should_be_supervised FROM game_types WHERE type_id = table_type_id;\n                IF (should_be_supervised = 1 AND NEW.staff_id IS NULL) THEN\n                    RAISE EXCEPTION 'Game type % should be supervised, missing dealer for session %',\n                        table_type_id, NEW.session_id;\n                ELSIF (should_be_supervised = 0 AND NEW.staff_id IS NOT NULL) THEN\n                    RAISE EXCEPTION 'Game type % should not be supervised, found dealer % for session %',\n                        table_type_id, NEW.staff_id, NEW.session_id;\n                END IF;\n                \n            END IF;\n            RETURN NULL;\n        END;\n    $ensure_dealer$ LANGUAGE plpgsql"
    )
    op.drop_entity(public_ensure_dealer_correct)

    # ### end Alembic commands ###
